import json
import logging
from pathlib import Path
from datetime import datetime
from engine.ai_engine import call_ai

log = logging.getLogger(__name__)

class LearningBrain:
    """
    Self-Learning System and Reviews (Section 11)
    """
    def __init__(self, data_dir: str = "data", reviews_dir: str = "reviews"):
        self.rules_file = Path(data_dir) / "learned_rules.json"
        self.stats_file = Path(data_dir) / "lifetime_stats.json"
        self.reviews_dir = Path(reviews_dir)
        
        self.rules = []
        self.stats = {}
        
        self.load_data()

    def load_data(self):
        if self.rules_file.exists():
            try:
                with open(self.rules_file, "r") as f:
                    content = f.read().strip()
                    if content:
                        self.rules = json.loads(content)
            except Exception as e:
                log.error(f"Could not load rules: {e}")
                
        if self.stats_file.exists():
            try:
                with open(self.stats_file, "r") as f:
                    content = f.read().strip()
                    if content:
                        self.stats = json.loads(content)
            except Exception as e:
                log.error(f"Could not load stats: {e}")

    def save_data(self):
        try:
            with open(self.rules_file, "w") as f:
                json.dump(self.rules, f, indent=2)
                
            with open(self.stats_file, "w") as f:
                json.dump(self.stats, f, indent=2)
        except Exception as e:
            log.error(f"Failed to save learning brain data: {e}")

    def run_daily_review(self, todays_trades: list):
        """DAILY SELF-REVIEW at 4:00 PM"""
        log.info("Running daily self-review...")
        
        prompt = (
            "Analyze these trades from today and lifetime stats. "
            "Identify what worked, what failed, mistakes made, rules to add, and tomorrow's adjustments.\n"
            f"Today's Trades: {json.dumps(todays_trades)}\n"
            f"Lifetime Stats: {json.dumps(self.stats)}\n\n"
            "Output JSON format:\n"
            "{\n"
            '  "what_worked": ["..."],\n'
            '  "what_failed": ["..."],\n'
            '  "mistakes_made": ["..."],\n'
            '  "new_rules": ["..."],\n'
            '  "tomorrow_adjustments": ["..."]\n'
            "}"
        )
        
        response = call_ai(prompt, max_tokens=1500)
        if response:
            try:
                review_data = json.loads(response)
                
                # Save daily review
                date_str = datetime.now().strftime("%Y-%m-%d")
                review_file = self.reviews_dir / f"daily_review_{date_str}.json"
                with open(review_file, "w") as f:
                    json.dump(review_data, f, indent=2)
                    
                # Store new learned rules
                for rule_text in review_data.get("new_rules", []):
                    self.rules.append({
                        "rule": rule_text,
                        "confidence": 5, # Initial medium confidence
                        "active": True,
                        "created_at": datetime.now().isoformat()
                    })
                    
                self.save_data()
                log.info(f"Daily review completed and saved to {review_file}")
                
            except Exception as e:
                log.error(f"Failed to parse or save daily review JSON: {e}")
        else:
            log.warning("Daily review AI call failed or returned None.")

    def run_weekly_review(self):
        """WEEKLY DEEP REVIEW every Sunday 8 PM"""
        log.info("Running weekly deep review...")
        date_str = datetime.now().strftime("%Y-%W")
        report_file = self.reviews_dir / f"weekly_improvement_report_{date_str}.txt"
        
        # In full implementation, this triggers another comprehensive AI call.
        try:
            with open(report_file, "w") as f:
                f.write(f"Weekly Review Report for {date_str}\n")
                f.write("Generated by NEXUS AI Trader v3.0\n")
            log.info(f"Weekly review initialized at {report_file}")
        except Exception as e:
            log.error(f"Failed to write weekly review: {e}")
